apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: microtx-handson-db1
spec:
  action: Create
  details:
    compartmentId: <自身のコンパートメントOCID>
    dbName: microtxhandson1
    displayName: oke-atp-handson-db1
    computeModel: ECPU
    computeCount: 2.0
    licenseModel: LICENSE_INCLUDED
    adminPassword:
      k8sSecret:
        name: admin-passwd
    dataStorageSizeInTBs: 1
  wallet:
    name: microtxhandson1
    password:
      k8sSecret:
        name: wallet-passwd
---
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: microtx-handson-db2
spec:
  action: Create
  details:
    compartmentId: <自身のコンパートメントOCID>
    dbName: microtxhandson2
    displayName: oke-atp-handson-db2
    computeModel: ECPU
    computeCount: 2.0
    licenseModel: LICENSE_INCLUDED
    adminPassword:
      k8sSecret:
        name: admin-passwd
    dataStorageSizeInTBs: 1
  wallet:
    name: microtxhandson2
    password:
      k8sSecret:
        name: wallet-passwd
